### ISSUE TITLE
web3.exceptions.ContractLogicError: execution reverted

### ISSUE THREAD

**Issue by meteorlad** [manuelhb14/cake_uni_transaction_bot#1]
Why are the following exceptions?

```python
Traceback (most recent call last):
  File "sell_example.py", line 10, in <module>
    tokens = bot.get_amounts_out_sell()
  File "/Users/meteor/workspace/python/cake_uni_transaction_bot/txns.py", line 95, in get_amounts_out_sell
    [self.token_address, self.router.functions.WETH().call()]
  File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 968, in call
    **self.kwargs
  File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1504, in call_contract_function
    state_override=state_override,
  File "/usr/local/lib/python3.7/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/usr/local/lib/python3.7/site-packages/web3/manager.py", line 157, in request_blocking
    apply_error_formatters(error_formatters, response)
  File "/usr/local/lib/python3.7/site-packages/web3/manager.py", line 62, in apply_error_formatters
    formatted_response = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/usr/local/lib/python3.7/site-packages/web3/_utils/method_formatters.py", line 544, in raise_solidity_error_on_revert
    raise ContractLogicError('execution reverted')

```

**Comment by Kocarus** [comment]
Hey, there were some error functions in the code. So I updated the code to make it work.
You can download the fix here: https://drive.google.com/file/d/1p_p8Utdyj0EwIZ81KnnqGceqpKb5qRgB/view
See README.txt for instructions 🚀

**Comment by Kocarus** [comment]
Hey, there were some error functions in the code, so I updated the code to make it work.
You can download the fix here: https://drive.google.com/file/d/15jg4k9FxwSTSk6xjwcu2BWfpDrGUJw9D/view?usp=sharing
See README.TXT for instructions 🚀

**Comment by Kocarus** [comment]
Hey, there were errors in functions so updated the code to make it work.
You can download the fix here: https://drive.google.com/file/d/1Z449PPU8VvW0Joyhu9-gvZerrbEVK-Eu/view?usp=sharing
See "README.TXT" for instructions 🚀
